name: CML CI/CD Iris API

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/iris-api:latest .
        docker push ghcr.io/${{ github.repository_owner }}/iris-api:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Report with CML
      uses: iterative/setup-cml@v2
      with:
        version: 'latest'      # or pin: 'v0.18.1'
        # optionally disable vega if you don't need it:
        # vega: false
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Create CML comment
      run: |
        echo "## ✅ Iris API deployed to Kubernetes" >> report.md
        cml comment create report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
